### PR TITLE
ENH: Cert and CA path options for Transport

### PR DESCRIPTION
**Pull request by Vovan-VE**
I guess next version will be 1.0.5, so I add `@since 1.0.5`. But I didn't change `version` in `composer.json` and didn't add tags as it is out of specific PR scope.

### CODE REVIEW

**Comment by Vovan-VE** [comment]
Implementation for #14.

**Comment by Vovan-VE** [comment]
I did check changes with self signed certificate provided by Xubuntu. The only tweaks over defaults was adding `127.0.0.1  xubuntu` to `/etc/hosts` and connecting to `https://xubuntu:8000` to pass host name verification.

**Comment by FZambia** [comment]
Thanks! @sl4mmer could you look at this?

**Comment by sl4mmer** [comment]
thanks @Vovan-VE 

@FZambia implementation is ok, i'm going to merge it today.

**Comment by FZambia** [comment]
@sl4mmer any update on this?

**Pull request merged**
