### PR TITLE
Fix tests not running

### PR DESCRIPTION
**Pull request by beporter**
The Travis CI builds for [centrifugal/phpcent](https://github.com/centrifugal/phpcent) are currently passing with a false positive. The tests are not actually being executed.

Example: https://travis-ci.org/centrifugal/phpcent/jobs/654707783#L247 (Look for "no tests executed".)

This PR corrects that issue by using the version of phpunit described by `composer.json` instead of the globally available copy preinstalled in the Travis environment.

It also adds notes on how to run the tests locally to the README.

Finally, it renames `phpunit.xml` to `phpunit.xml.dist` as is [recommended by the PHPUnit docs](https://phpunit.readthedocs.io/en/9.0/textui.html) (search for `--configuration`).

### CODE REVIEW

**Comment by FZambia** [comment]
@beporter many thanks for your contributions!

**Comment by beporter** [comment]
Happy to help! Thanks for the quick turnaround. That might be the fastest I've ever seen a contribution merged. 👍 

I noticed something weird with the composer package that I thought I should mention: The [Packagist page](https://packagist.org/packages/centrifugal/phpcent) is showing the 3.0.2 readme (with the new testing instructions) and the updated build badge, but the page is not listing 3.0.2 as an available download yet. 🤔

**Comment by FZambia** [comment]
Let's wait till tomorrow, there is a chance that it will be updated very soon. If nothing change - will take a closer look.

**Comment by FZambia** [comment]
Was my mistake during release actually, I forgot to update version in composer.json file. Recreated tag.

**Pull request merged**
