### PR TITLE
Improve Client

### PR DESCRIPTION
**Pull request by xAockd**
In case of error, we don't have response.
Actually, we don't have response at all here.

### CODE REVIEW

**Comment by FZambia** [comment]
@xAockd thanks! Will create tag release soon as I get home

**Comment by FZambia** [comment]
@xAockd I reverted your pull request because there is no $response variable in local scope.

**Comment by FZambia** [comment]
I suppose we can use $data in that place right?

**Comment by xAockd** [comment]
it will be empty(false) in this case. Everything will be in curl error I suppose.

**Comment by xAockd** [comment]
btw, you are using safety as static variable but set as a property. I don't the reason to use it as a static property. And I would keep **request** method as protected. Someone might want to extend it and rewrite, like me for instance :)

**Comment by FZambia** [comment]
Could you send pr with this change? Will really appreciate this as I am not a PHP programmer at all.

**Comment by FZambia** [comment]
Made a tag v2.0.1 with this fix

**Comment by xAockd** [comment]
I will try to find time for contribution.

**Pull request merged**
