### PR TITLE
Add meta data support in jwt token

### PR DESCRIPTION
**Pull request by BaBL86**
My server has "proxy_include_connection_meta" option and I can't set meta data through this library. Only info.

This PR fixed this issue.

### CODE REVIEW

**Comment by FZambia** [comment]
Hello @BaBL86, thanks. I am not sure why CI fails here to be honest. It works fine for the master branch. Could you merge the master to your branch - I added `docker ps` step to CI to make sure container with Centrifugo is starting.

**Comment by BaBL86** [comment]
Yes, passed now

**Comment by FZambia** [comment]
No idea why it was failing, but definitely not the issue from this PR. Many thanks!

**Comment by FZambia** [comment]
Released as part of https://github.com/centrifugal/phpcent/releases/tag/v5.1.0

**Pull request merged**
